databases:
  - name: useradmin
    databaseName: useradmin
    user: useradmin
    plan: free

services:
  - type: web
    name: useradmin
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails db:migrate && bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: useradmin
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
